import { NextRequest } from "next/server";
import { prisma } from "@/lib/prisma";
import { verifyJwt, JwtPayload } from "@/lib/jwt";
import { apiSuccess, apiError } from "@/lib/api-response";
import {
  checkoutOrderSchema,
  idempotencyKeyHeaderSchema,
} from "@/lib/validations/order";
import {
  createRazorpayOrder,
  generateOrderId,
  getRazorpayKeyId,
} from "@/lib/payment/razorpay";
import { LicenseType } from "@prisma/client";

export const dynamic = "force-dynamic";

/**
 * POST /api/v1/orders/checkout
 *
 * Initiates a purchase transaction.
 * Creates an internal Order in status PENDING and initializes a Razorpay Order.
 *
 * Security & Integrity:
 *   - Requires authenticated active user.
 *   - Strictly validates product is PUBLISHED.
 *   - Derives amount authoritatively from PostgreSQL database (ignores client amounts).
 *   - Captures price and product snapshots in Order and OrderItem.
 *   - Enforces idempotent order creation using database-level unique constraints.
 *   - Initializes Razorpay order with exact integer paise.
 *   - Never marks orders as PAID, never creates entitlements, never provisions downloads.
 *   - Zero sensitive data leakage (no secrets, no database credentials, no PAN/bank info).
 */
export async function POST(req: NextRequest) {
  try {
    // 1. Authenticate user session
    const authHeader = req.headers.get("authorization");
    if (!authHeader) {
      return apiError(
        "UNAUTHORIZED",
        "Authentication is required to initiate checkout",
        401
      );
    }

    const parts = authHeader.split(" ");
    if (parts.length !== 2 || parts[0] !== "Bearer" || !parts[1]) {
      return apiError(
        "UNAUTHORIZED",
        "Invalid authorization header format",
        401
      );
    }

    const token = parts[1].trim();
    const payload = verifyJwt<JwtPayload>(token);
    if (!payload || !payload.sub) {
      return apiError(
        "UNAUTHORIZED",
        "Invalid or expired authentication token",
        401
      );
    }

    const authUser = await prisma.user.findUnique({
      where: { id: payload.sub },
      select: {
        id: true,
        email: true,
        fullName: true,
        role: true,
        isActive: true,
      },
    });

    if (!authUser) {
      return apiError(
        "UNAUTHORIZED",
        "Authenticated user not found",
        401
      );
    }

    if (!authUser.isActive) {
      return apiError(
        "FORBIDDEN",
        "Your account is inactive or suspended. Cannot initiate checkout.",
        403
      );
    }

    // 2. Parse and validate request payload
    let rawBody: unknown;
    try {
      rawBody = await req.json();
    } catch {
      return apiError(
        "VALIDATION_FAILED",
        "Invalid JSON format in request body",
        400
      );
    }

    const parseResult = checkoutOrderSchema.safeParse(rawBody);
    if (!parseResult.success) {
      return apiError(
        "VALIDATION_FAILED",
        "Invalid checkout request payload",
        400,
        parseResult.error.errors.map((e) => ({
          field: e.path.join("."),
          message: e.message,
        }))
      );
    }

    const { productId, licenseType, idempotencyKey: bodyIdempotencyKey } =
      parseResult.data;

    // 3. Extract and validate header-based idempotency key if present
    const headerIdempotencyKey =
      req.headers.get("idempotency-key") ||
      req.headers.get("x-idempotency-key");

    let finalIdempotencyKey = bodyIdempotencyKey || null;

    if (headerIdempotencyKey) {
      const headerKeyParsed = idempotencyKeyHeaderSchema.safeParse(
        headerIdempotencyKey
      );
      if (!headerKeyParsed.success) {
        return apiError(
          "VALIDATION_FAILED",
          "Invalid idempotency key format in request headers",
          400,
          headerKeyParsed.error.errors.map((e) => ({
            field: "idempotencyKey",
            message: e.message,
          }))
        );
      }
      if (!finalIdempotencyKey) {
        finalIdempotencyKey = headerKeyParsed.data;
      }
    }

    // 4. Idempotency Check: Return existing order if key was already processed
    if (finalIdempotencyKey) {
      const existingOrder = await prisma.order.findUnique({
        where: { idempotencyKey: finalIdempotencyKey },
        include: {
          items: true,
        },
      });

      if (existingOrder) {
        // Enforce user boundary: idempotency key belongs to this user
        if (existingOrder.buyerId !== authUser.id) {
          return apiError(
            "FORBIDDEN",
            "Idempotency key was generated by another user session",
            403
          );
        }

        return apiSuccess(
          {
            orderId: existingOrder.id,
            totalAmountPaise: existingOrder.totalAmountPaise,
            currency: existingOrder.currency,
            razorpayOrderId: existingOrder.razorpayOrderId,
            razorpayKeyId: getRazorpayKeyId(),
            product: {
              title: existingOrder.items[0]?.productTitle,
              pricePaise: existingOrder.totalAmountPaise,
            },
            customer: {
              name: existingOrder.buyerNameSnapshot,
              email: existingOrder.buyerEmailSnapshot,
            },
          },
          "Existing order session retrieved via idempotency key",
          200
        );
      }
    }

    // 5. Query and validate product from PostgreSQL
    const product = await prisma.product.findUnique({
      where: { id: productId },
      select: {
        id: true,
        title: true,
        pricePaise: true,
        discountPricePaise: true,
        isFree: true,
        status: true,
        sellerId: true,
        seller: {
          select: {
            id: true,
            status: true,
          },
        },
      },
    });

    if (!product) {
      return apiError("NOT_FOUND", "Product not found", 404);
    }

    if (product.status !== "PUBLISHED") {
      return apiError(
        "PRODUCT_NOT_AVAILABLE",
        `Product cannot be purchased because its current status is '${product.status}'`,
        400
      );
    }

    if (product.seller.status !== "APPROVED") {
      return apiError(
        "SELLER_NOT_ACTIVE",
        "Product cannot be purchased because the creator store is not currently active",
        400
      );
    }

    // 6. Authoritative price calculation (ignoring any client-sent price)
    let subtotalPaise = product.pricePaise;
    let discountPaise = 0;
    let totalAmountPaise = product.pricePaise;

    if (product.isFree) {
      totalAmountPaise = 0;
      subtotalPaise = 0;
      discountPaise = 0;
    } else if (
      product.discountPricePaise !== null &&
      product.discountPricePaise !== undefined &&
      product.discountPricePaise >= 0 &&
      product.discountPricePaise < product.pricePaise
    ) {
      totalAmountPaise = product.discountPricePaise;
      discountPaise = product.pricePaise - product.discountPricePaise;
    }

    // Platform fee calculation (10% of total charged amount)
    const platformFeePaise = Math.round(totalAmountPaise * 0.1);
    const sellerEarningsPaise = totalAmountPaise - platformFeePaise;

    // 7. Generate unique internal order ID
    const orderId = generateOrderId();

    // 8. Initialize Razorpay order via payment gateway provider
    let rzpOrder;
    try {
      rzpOrder = await createRazorpayOrder({
        orderId,
        amountPaise: totalAmountPaise,
        currency: "INR",
        productId: product.id,
        buyerEmail: authUser.email,
        buyerName: authUser.fullName,
      });
    } catch (rzpErr) {
      console.error("[CHECKOUT_RAZORPAY_INIT_ERROR]", rzpErr);
      return apiError(
        "PAYMENT_GATEWAY_ERROR",
        "Failed to initialize payment gateway order. Please try again.",
        502
      );
    }

    // 9. Persist Order and OrderItem atomically in a PostgreSQL transaction
    try {
      const order = await prisma.$transaction(async (tx) => {
        // Re-verify product status inside atomic transaction lock
        const fresh = await tx.product.findUnique({
          where: { id: product.id },
          select: { status: true },
        });

        if (!fresh || fresh.status !== "PUBLISHED") {
          throw new Error("PRODUCT_UNPUBLISHED");
        }

        return tx.order.create({
          data: {
            id: orderId,
            buyerId: authUser.id,
            subtotalPaise,
            discountPaise,
            platformFeePaise,
            totalAmountPaise,
            currency: "INR",
            status: "PENDING",
            razorpayOrderId: rzpOrder.razorpayOrderId,
            buyerNameSnapshot: authUser.fullName,
            buyerEmailSnapshot: authUser.email,
            idempotencyKey: finalIdempotencyKey,
            items: {
              create: {
                productId: product.id,
                sellerId: product.sellerId,
                productTitle: product.title,
                pricePaise: totalAmountPaise,
                platformFeePaise,
                sellerEarningsPaise,
                licenseType: licenseType as LicenseType,
              },
            },
          },
          include: {
            items: true,
          },
        });
      });

      return apiSuccess(
        {
          orderId: order.id,
          totalAmountPaise: order.totalAmountPaise,
          currency: order.currency,
          razorpayOrderId: order.razorpayOrderId,
          razorpayKeyId: rzpOrder.keyId,
          product: {
            title: product.title,
            pricePaise: order.totalAmountPaise,
          },
          customer: {
            name: authUser.fullName,
            email: authUser.email,
          },
        },
        "Checkout order initialized successfully",
        201
      );
    } catch (dbErr: any) {
      if (dbErr.message === "PRODUCT_UNPUBLISHED") {
        return apiError(
          "PRODUCT_NOT_AVAILABLE",
          "Product was unpublished or removed prior to checkout completion",
          400
        );
      }

      // Handle race condition: another concurrent request inserted the same idempotencyKey
      if (dbErr.code === "P2002" && finalIdempotencyKey) {
        const racedOrder = await prisma.order.findUnique({
          where: { idempotencyKey: finalIdempotencyKey },
          include: { items: true },
        });

        if (racedOrder) {
          return apiSuccess(
            {
              orderId: racedOrder.id,
              totalAmountPaise: racedOrder.totalAmountPaise,
              currency: racedOrder.currency,
              razorpayOrderId: racedOrder.razorpayOrderId,
              razorpayKeyId: rzpOrder.keyId,
              product: {
                title: product.title,
                pricePaise: racedOrder.totalAmountPaise,
              },
              customer: {
                name: authUser.fullName,
                email: authUser.email,
              },
            },
            "Order retrieved from concurrent idempotent session",
            200
          );
        }
      }

      console.error("[CHECKOUT_TRANSACTION_ERROR]", dbErr);
      return apiError(
        "INTERNAL_SERVER_ERROR",
        "An unexpected error occurred while saving the checkout order",
        500
      );
    }
  } catch (error) {
    console.error("[CHECKOUT_API_ERROR]", error);
    return apiError(
      "INTERNAL_SERVER_ERROR",
      "An unexpected error occurred during checkout initialization",
      500
    );
  }
}
